{% set name = "ratarmountcore" %}
{% set version = "0.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ratarmountcore-{{ version }}.tar.gz
  sha256: 9aa747ffe967d805c6635a798241ccea9382cb629d21a93475d0c62e9c853a60

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - dataclasses
    - importlib-metadata
  run_constrained:
    - indexed_gzip >=1.6.3,<2
    - indexed_zstd >=1.3.1,<2
    - python-libarchive-c >=5.1,<6
    - python-xz >=0.4,<0.5
    - rarfile =4.*

test:
  imports:
    - ratarmountcore
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/mxmlnkn/ratarmount/tree/master/core
  summary: Random Access Read-Only Tar Mount Library
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ap--
    - mxmlnkn
